server {
    listen 22825;
    listen [::]:22825;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri/ $uri/index.html /index.html;
    }
}
