import type { ReactNode } from 'react';

import { Manrope } from 'next/font/google';

import LayoutProvider from '@app/modules/shared/LayoutProvider';
import cn from '@app/modules/utils/cn';

import './globals.css';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cn(
          manrope.className,
          'mx-auto max-w-screen-lg bg-black p-4 text-neutral-100 md:p-6',
        )}
      >
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
